version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./../:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      code-networks:
        ipv4_address: 10.7.0.7
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./../:/var/www/html
    networks:
      code-networks:
        ipv4_address: 10.7.0.8
  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=my_app
      - MYSQL_ROOT_PASSWORD=secret
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    networks:
      code-networks:
        ipv4_address: 10.7.0.9

networks:
  code-networks:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.0.0/16
          gateway: 10.7.0.1