openapi: "3.0.0"
info:
  version: 1.0.0
  title: Events API
  description: |
    EventAPI using cakePHP
servers:
  - url: /
paths:
  /events:
    post:
      tags:
        - Events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventsResponse'
components:
  schemas:
    Event:
      type: object
      properties:
        eventName:
          type: string
          required: true
          example: event 1
        duration:
          type: integer
          required: true
          example: 30
        startDateTime:
          type: string
          format: date-time
          required: true
          example: 2021-02-13 01:00
        endDateTime:
          type: string
          format: date-time
          example: 2021-02-13 07:00
        frequency:
          type: string
          enum: [Once-Off, Weekly, Monthly]
          required: true
        invitees:
          type: array
          items:
            type: integer
          required: true
          example: [1,2,3,4]
    EventsResponse:
      allOf:
        - type: object
          properties:
            id:
              type: integer
          required:
            - id
        - $ref: '#/components/schemas/Event'
